apiVersion: v1
kind: Deployment
metadata:
  name: nginx-web
spec:
  selector:
    matchLabels:
      run: nginx-web
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx-web
    spec:
      containers:
      - name: nginx-web
        image: 172.17.0.16:5000/mk/test:latest
        ports:
        - containerPort: 80
