apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-web
spec:
  replicas: 2
  selector:
    name: nginx-web
  template:
    metadata:
      labels:
        name: nginx-web
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
        - name: nginx-web
          image: <IMAGE_TAG>
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-web-service
spec:
  ports:
    - port: 80
  selector:
    name: nginx-web