apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-web
spec:
  replicas: 2
  selector:
    name: nginx-web
  template:
    metadata:
      labels:
        name: nginx-web
    spec:
      imagePullSecrets:
      - name: registry-secret
      containers:
        - name: nginx-web
          image: <IMAGE_TAG>
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      minReadySeconds: 5
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 1