apiVersion: v1
kind: Deployment
metadata:
  name: nginx-web
spec:
  selector:
    matchLabels:
      run: nginx-web
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx-web
    spec:
      containers:
      - name: nginx-web
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-web
  labels:
    run: nginx-web
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: nginx-web